version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: bdd-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./web
    container_name: web-interface-bdd
    restart: always
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - mysql
