version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mon-projet-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
